CREATE TABLE STAFF ( 

S_ID NUMBER (8) NOT NULL, 

S_FNAME VARCHAR2(20) NOT NULL, 

S_LNAME VARCHAR2(20) NOT NULL, 

S_PHONENUMBER VARCHAR2 (20) NOT NULL, 

S_B_ADDRESS VARCHAR2 (50) NOT NULL, 

CONSTRAINT STAFF_PK PRIMARY KEY(S_ID), 

CONSTRAINT STAFF_FK (S_B_ADDRESS) FOREIGN KEY REFERENCES BRANCH (B_ADDRESS)); 

 

/* -- */ 

 

CREATE TABLE BRANCH ( 

B_ID NUMBER (8) NOT NULL, 

B_ADDRESS VARCHAR2 (50) NOT NULL, 

CONSTRAINT BRANCH_PK PRIMARY KEY (B_ID)); 

 

/* -- */ 

 

CREATE TABLE CUSTOMERS ( 

C_ID NUMBER (8) NOT NULL, 

C_FNAME VARCHAR2(20) NOT NULL, 

C_LNAME VARCHAR2(20) NOT NULL, 

C_ADDRESS VARCHAR2(50) NOT NULL, 

C_PHONENUMBER VARCHAR2 (20) NOT NULL, 

CONSTRAINT CUSTOMERS_PK PRIMARY KEY(C_ID)); 

 

/* -- */ 

 

CREATE TABLE RESERVATIONS ( 

R_ID NUMBER (8) NOT NULL, 

R_C_ID NUMBER (8) NOT NULL, 

R_S_ID NUMBER (8) NOT NULL, 

CHECK_IN DATE NOT NULL, 

CHECK_OUT DATE NOT NULL, 

CONSTRAINT RESERVATIONS_PK PRIMARY KEY(R_ID), 

CONSTRAINT RESERVATIONS_FK (R_C_ID) FOREIGN KEY REFERENCES CUSTOMERS(C_ID), 

CONSTRAINT RESERVATIONS_FK (R_S_ID) FOREIGN KEY REFERENCES STAFF(S_ID)); 

 

/* -- */ 

 

CREATE TABLE RENTAL ( 

RE_ID NUMBER (15) NOT NULL, 

RE_C_ID NUMBER (8) NOT NULL, 

RE_BK_ID NUMBER (8) NOT NULL, 

CHECK_IN DATE (8) NOT NULL, 

CHECK_OUT DATE (8) NOT NULL, 

CONSTRAINT RENTAL_PK PRIMARY KEY(RE_ID), 

CONSTRAINT RENTAL_FK (RE_C_ID) FOREIGN KEY REFERENCES CUSTOMERS(C_ID), 

CONSTRAINT RENTAL_FK (RE_BK_ID) FOREIGN KEY REFERENCES BOOKS(BK_ID)); 

 

 

/* -- */ 

 

CREATE TABLE BOOKS ( 

BK_ID NUMBER (8) NOT NULL, 

BK_NAME VARCHAR2 (20) NOT NULL, 

BK_PUBLISHER VARCHAR2(20) NOT NULL, 

BK_AUTHOR VARCHAR2(20) NOT NULL, 

BK_YEAR NUMBER (8) NOT NULL, 

BK_GENRE VARCHAR2 (20) NOT NULL, 

BK_R_ID NUMBER (15) NOT NULL, 

CONSTRAINT BOOKS_PK PRIMARY KEY(BK_ID), 

CONSTRAINT BOOKS_FK (BK_R_ID) FOREIGN KEY REFERENCES RESERVATIONS(R_ID)); 

/*--*/


CREATE TABLE BRANCH ( 

B_ID NUMBER (8) NOT NULL, 

B_ADDRESS VARCHAR2 (50) NOT NULL, 

CONSTRAINT BRANCH_PK PRIMARY KEY (B_ID)); 

 

/* -- */ 

 

CREATE CUSTOMERS ( 

C_ID NUMBER (8) NOT NULL, 

C_FNAME VARCHAR2(20) NOT NULL, 

C_LNAME VARCHAR2(20) NOT NULL, 

C_ADDRESS VARCHAR2(50) NOT NULL, 

C_PHONENUMBER VARCHAR2 (20) NOT NULL, 

CONSTRAINT CUSTOMERS_PK PRIMARY KEY(C_ID)); 
